# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cServer.Thread', unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set([('name', 'computer')]),
        ),
    ]
