# Generated by Django 2.2.4 on 2019-08-20 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cServer', '0003_auto_20190815_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='lastping',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 0, 52, 37, 498210)),
            preserve_default=False,
        ),
    ]
